name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - et     # change back to `master` after upstreaming
  pull_request:
    branches:
      - et     # change back to `master` after upstreaming

jobs:
  build:
    uses: ./.github/workflows/build-reusable.yaml
    with:
      artifact-name: build
      target: '["rv64imfc-lp64f"]'
      os: '["ubuntu-24.04"]'
      mode: '["newlib"]'
      cmodel: '["medany"]'
      languages: '["c,c++"]'
      report: false

  test-sim:
    # disable until upstreamed
    if: ${{ false }}
    uses: ./.github/workflows/build-reusable.yaml
    with:
      artifact-name: sim
      os: '["ubuntu-24.04"]'
      mode: '["newlib"]'
      target: '["rv64gc-lp64d"]'
      sim: '["spike"]'

  build-multilib:
    if: ${{ false }} # Disable until multilib errors are triaged
    uses: ./.github/workflows/build-reusable.yaml
    with:
      artifact-name: multilib
      os: '["ubuntu-24.04"]'
      mode: '["newlib","linux"]'
      target: '["rv64gc-lp64d"]'

